### ISSUE TITLE
# Common Jira - To include scripts and folders

### ISSUE THREAD

**Issue by praqmaTim** [Praqma/code-utils#16]
Several of us agreed on slack that it would be a good idea to have a place to keep useful
Jira queries. Many of us have quite a few and there is no reason not to share them.

**Comment by buep** [comment]
Thanks @praqmaTim - will you add the first filters, since you estimated it and prioritized this issue?

You can assign back to me, @JKrag or the other who have filters afterwards.

I would very much like a subdirectory called "jirafilters" and a readme under there with one section pr. filter. The root repo readme should as in several other example point to the subdir.

The jirafilters/README.md should have a section pr. filter/or group of filter - what-ever make sense, and explain as with talked about:
* use-case, or idea behind the filter
* required plugins and special configuraitons if any

**Comment by praqmaTim** [comment]
@buep  I was thinking that maybe we have a sub directory called Jira. Within that we have jirafilters and whatever else jira related we want to share. I think I have some script runner scripts that could be shared also.  Of course, each with its own Readme. Will do the sections as you suggest. Probably next week before I look at it. I have a customer today and another one tomorrow, then out at DSV rest of the week.

**Comment by buep** [comment]
>  sub directory called Jira. Within that we have jirafilters and whatever else jira related we want to share.

Sounds good!

**Comment by buep** [comment]
Taking this over - I want to get rid of  my filters, currently saved on mail. Assigning back to you again after @praqmaTim so you can add yours later.

**Comment by buep** [comment]
pushed my changes on the branch, back to you again @praqmaTim

**Comment by buep** [comment]
Time logging: https://praqma.fogbugz.com/f/cases/15329/cude-utils-Common-Jira-To-include-scripts-and-folders-16
